export class StorageMock {
  constructor() { this.transcripts = []; this.metadb = {}; this.detections = {}; }
  async save(transcription) { this.transcripts.push(transcription); return true; }
  async saveMetadata(id, meta) { this.metadb[id] = Object.assign(this.metadb[id] || {}, meta); return true; }
  async saveDetection({ recordingId, detection }) { this.detections[recordingId] = detection; return true; }
  all() { return { transcripts: this.transcripts, meta: this.metadb, detections: this.detections }; }
}

export class TranscriptionAPIMock {
  constructor() { this.counter = 0; }
  async transcribe(_audio) {
    this.counter++;
    return { id: `rec-${this.counter}`, text: 'This is a mocked transcription. It might have been generated by an LLM. It mentions GPT and AI.' };
  }
}